import Head from "next/head";
import Link from "next/link";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import vg from "../public/Medicine-amico.svg";
import Image from "next/image";

export default function Home() {
  const notify = () =>
    toast("Wow so Easy!", {
      position: "top-center",
      autoClose: 5000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "dark",
    });
  return (
    <div>
      <button onClick={notify} className="">
        {" "}
        Notify !{" "}
      </button>
      <ToastContainer />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-3xl font-bold text-primary">
        <Link href="login"> Ingresar </Link>
        Welcome to <a href="">MyDocRminder</a>
      </main>
      <section>
        <Image src={vg} />
      </section>
    </div>
  );
}
